version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/iosr
hooks:
  ApplicationStop:
    - location: codeDeploy_scripts/ApplicationStop2.sh
  BeforeInstall:
    - location: codeDeploy_scripts/BeforeInstall.sh
  ApplicationStart:
    - location: codeDeploy_scripts/ApplicationStart.sh