version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y python-pip
      - pip install -r req.txt
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ls
      - python buildspec.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'